version: "3.4"
services:
  docbot:
    build:
      context: .
    environment:
      DEPLOYMENT: ${DEPLOYMENT}
      DOCBOT_LOG_LEVEL: ${DOCBOT_LOG_LEVEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX_NAME: ${PINECONE_INDEX_NAME}
    ports:
      - "8501:8501"
